### ISSUE TITLE
app channel is not initialized

### ISSUE THREAD

**Issue by pchao01** [PacktPublishing/Practical-Microservices-with-Dapr-and-.NET#5]
I got this error while trying to run chapter03 grpc sample :
Dapr.Client.InvocationException: Exception while invoking reserve on appId:reservation-service
 ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="app channel is not initialized")
   at Dapr.Client.DaprClientGrpc.MakeInvokeRequestAsyncWithResponse[TRequest,TResponse](InvocationRequest`1 request, Boolean useRaw, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Dapr.Client.DaprClientGrpc.MakeInvokeRequestAsyncWithResponse[TRequest,TResponse](InvocationRequest`1 request, Boolean useRaw, CancellationToken cancellationToken)
   at Dapr.Client.DaprClientGrpc.InvokeMethodAsync[TRequest,TResponse](String appId, String methodName, TRequest data, HTTPExtension httpExtension, CancellationToken cancellationToken)
   at sample.microservice.order.Controllers.OrderController.SubmitOrder(Order order, DaprClient daprClient) in C:\chsarp\dapr-samples\chapter03\chapter03\sample.microservice.order\Controllers\OrderController.cs:line 36
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br
Cookie: ASP.NET_SessionId=aihc3wnuy0pub10ujqlklsy1
Host: 127.0.0.1:5001
User-Agent: PostmanRuntime/7.26.8
traceparent: 00-d09c700d1e38a425454a18dc08ac53b7-14f70be2d4a6bfb1-01
Content-Length: 214
Postman-Token: 67f1d1b8-4319-4b66-96af-aa6680c220f8

**Comment by DavideBedin** [comment]
Can you successfully launch the reservation-service via dapr CLI? The command is in launch.ps1 `dapr run --app-id "reservation-service" --app-port "3000" --app-protocol grpc --dapr-http-port "5020" --dapr-grpc-port "50020" -- dotnet run --project ./sample.microservice.reservation-grpc/sample.microservice.reservation-grpc.csproj --urls="http://+:3000"`

**Comment by dabedin** [comment]
@packt-pradeeps can we close this issue?

**Comment by packt-pradeeps** [comment]
Yes

**Comment by pchao01** [comment]
ok

傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2021 年 7月 月 8 日週四，時間：19:42 ， Davide Bedin ***@***.***> 寫道：   


@packt-pradeeps can we close this issue?
